debug: false
trace: false
logging:
  level:
    root: info
    org.springframework: info
    org.springframework.web: info
    io.github.syakuis: trace
server:
  port: 8080
spring:
  main:
    banner-mode: console
  devtools:
    livereload:
      enabled: true